version: '3.9'
services:
  postgresql:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: connect
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"